"""add column categoria in cor

Revision ID: d687b2b9ebd5
Revises: d01ef57eaa8b
Create Date: 2026-07-22 21:15:05.638586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd687b2b9ebd5'
down_revision: Union[str, Sequence[str], None] = 'd01ef57eaa8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cores', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cores', 'categoria')
    # ### end Alembic commands ###
