"""fist migration

Revision ID: d01ef57eaa8b
Revises: 
Create Date: 2026-07-22 17:37:22.757009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01ef57eaa8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('dia_inteiro', sa.Boolean(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fim', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('dataNascimento', sa.Date(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('cores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_hex', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=False),
    sa.Column('horario_termino', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('presenca_confirmada', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('id_cor', sa.Integer(), nullable=True),
    sa.Column('preco_momento', sa.Float(), nullable=False),
    sa.Column('duracao_momento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_agendamento'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['id_cor'], ['cores.id'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['agendamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('agendamento_servico')
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('cores')
    op.drop_table('clientes')
    op.drop_table('bloqueios')
    # ### end Alembic commands ###
